var defaultValues = { name: "verticalscroller1", effectwidth: 200, effectheight: 100, scrollingspeed: 2, font: "Verdana", fontstyle: "bold", fontsize: "18", textcolor: "#00007f", backgroundcolor: "#ffffff", usesidefading: true, spaces: 5, text: "This is Vertical Scroller... Display a large amount of text in a compact way on your site. You can even have <a href=\"http://www.effectmaker.com/clickpage.html\">links</a>!! Get it today together with the Effect Maker...", waitperiod: 1000, maxscrollingspeed: 10, fps: 20 };
var configuration = new Array();
configuration[0] = new ConfiguratorItem(configurator.TEXTFIELD, 'name', 'General', 'Configuration save name', 'The name that will be used to save this configuration. Do not use space characters here.', false);
configuration[1] = new ConfiguratorItem(configurator.TEXTFIELD, 'effectwidth', 'General', 'Effect Width', 'The width of the whole effect in pixels', true);
configuration[2] = new ConfiguratorItem(configurator.TEXTFIELD, 'effectheight', 'General', 'Effect Height', 'The height of the whole effect in pixels', true);
configuration[3] = new ConfiguratorItem(configurator.TEXTAREA, 'text', 'Text', 'Text', 'The text to be included in the scroller.', false);
configuration[4] = new ConfiguratorItem(configurator.FONTFIELD, 'font', 'Font', 'Font', 'Fonts to use with the text, select safe fonts or write the name of a custom font. Clear the field to see a dropdown of web safe fonts to use.');
configuration[5] = new ConfiguratorItem(configurator.CHOICEFIELD, 'fontstyle', 'Font', 'Font style', 'The style of the font: normal, bold, italic, oblique.', false, new Array('normal', 'bold', 'italic', 'oblique'));
configuration[6] = new ConfiguratorItem(configurator.TEXTFIELD, 'fontsize', 'Font', 'Font size', 'Size of the text font', true);
configuration[7] = new ConfiguratorItem(configurator.COLORFIELD, 'textcolor', 'Font', 'Text Color', 'The color of the text.');
configuration[8] = new ConfiguratorItem(configurator.TEXTFIELD, 'scrollingspeed', 'Scrolling', 'Scrolling Speed', 'The speed of the text.', true);
configuration[9] = new ConfiguratorItem(configurator.TEXTFIELD, 'spaces', 'Other', 'Spaces after message', 'The number of blank lines after the text.', true);
configuration[10] = new ConfiguratorItem(configurator.CHECKBOX, 'usesidefading', 'Other', 'Use side fading', 'The text will fade out at the top and bottom.');
configuration[11] = new ConfiguratorItem(configurator.COLORFIELD, 'backgroundcolor', 'Other', 'Background color', 'Used for the side fading effect, should be the background color of the page.');
configuration[12] = new ConfiguratorItem(configurator.TEXTFIELD, 'waitperiod', 'Scrolling', 'Wait period mouse over', 'A variable used for letting the scroller wait a while after the user manually browsed the text, before it starts to automatically scroll the text again.', true);
configuration[13] = new ConfiguratorItem(configurator.TEXTFIELD, 'maxscrollingspeed', 'Scrolling', 'Max scrolling speed', 'Maximum scrolling speed when the user is browsing the text.', true);
configuration[14] = new ConfiguratorItem(configurator.TEXTFIELD, 'fps', 'Scrolling', 'Frames per second', 'Frames per second for the effect.', true);
